language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm run build
before_deploy:
- git config --local user.name "wxrbwran"
- git config --local user.email "wxrbw@qq.com"
before_install:
- openssl aes-256-cbc -K $encrypted_38fc768319ec_key -iv $encrypted_38fc768319ec_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 123.206.90.112\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ssh ubuntu@123.206.90.112 'cd ~/sites/web-admin &&git pull &&yarn & npm run build'
